### ISSUE TITLE
Moving direction

### ISSUE THREAD

**Issue by nibelungen** [pageauc/motion-track#4]
Hi @pageauc,

you compared your script with this one https://github.com/gregtinkers/carspeed.py but does your script analyze the direction too? I tried yours but get strange results if the vehicle moves from LTR, RTL works good - another point is the distance from the vehicles from LTR, we would need a diffrent value for image view ft would differ 1 to 3 meters. Maybe the distance is too short? Got only 13,5 meter.

best regards
andreas

**Comment by pageauc** [comment]
Direction is not displayed but can be inferred by positional data.  ie x position increasing from low to high or reverse.  This could be added in the logic.  Position differences are computed using absolute values.  I have not found any issues with data in either direction since it is the same calculation used.  Are you using latest version located here https://github.com/pageauc/rpi-speed-camera
The program does not correct for the fact that the vehicles in the opposite lanes are at a different distance away from the camera.  This may be part of your problem.  You can reduce this issue by averaging calibration for vehicles going in different directions.  If I get a chance I will look at separate calibration data for vehicles in road lanes going in different directions.  This could represent maybe 8 ft difference in distance away
If you still feel there are significant problems (assuming you have correctly calibrated your setup) then attach a copy of debug log information.
Claude ...

**Comment by pageauc** [comment]
Please Note this repository has been moved to https://github.com/pageauc/rpi-speed-camera
This makes it easier to manage and track with own wiki (not yet implemented)
