### ISSUE TITLE
Variables not consistent in script/doc

### ISSUE THREAD

**Issue by bsiege** [pageauc/motion-track#5]
there is some confusion because in config is 
**IMAGE**_VIEW_FT = 72     # Set the width in feet for the road width that the camera width sees

But mostly it is described as 
Readme.md:\* Use formula below to calculate a value for **IMG**_VIEW_FT variable

**Comment by pageauc** [comment]
Thanks.  This is definitely my error since I renamed the variable when I implemented the config.py file.  I am working on eliminating (supplementing) the need for manual calibration.  Since small vehicles are within a specific size it is possible to monitor traffic for a while looking for smaller vehicles and check the ratio of W and H to make sure it is right shape.  Since small cars are normally within a certain length then these readings can be used to calibrate the distance.  It would have to run for a while to get enough vehicles.  Also looking a changing format for CSV data file and possible making a web interface for easier review of data.  Might look at putting data into a SQL database but since this is just a demo I might make a new version specific for vehicles. 

It is possible to track any type of moving objects and not just vehicles.  A profile could be set to look for certain W/H ratios and square pixel areas between specific min and max values.  Some users apparently are using it to track things like birds or insects.  

If you have a project I would be pleased to hear about it.  
This program was just done as a personal challenge and was written as a demo that other users could adapt for their needs.  I just used vehicles in the demo since it was easy and kind of useful for testing.

Thanks again.  Claude ...

**Comment by pageauc** [comment]
Corrected readme.md file and updated github repo

**Comment by bsiege** [comment]
On 10.10.16 15:54, Claude Pageau wrote:

> Thanks. This is definitely my error since I renamed the variable when
> I implemented the config.py file. I am working on eliminating
> (supplementing) the need for manual calibration.

Yes, this would help because i have a v2 camera and the calibration
value makes no sense but the output seems to be quite accurate.
I think it has to do with the different optic:

Original RPi camera (v1.3) OmniVision OV5647
Lens: f=3.6 mm, f/2.9
Angle of View: 54 x 41 degrees

New Rpi camera (v2.1) Sony IMX219
Lens: f=3.04 mm, f/2.0
Angle of view: 62.2 x 48.8 degrees

And I forgot to mention: I made a grep over the whole directory of
speed-track-2 and also the script speed.py is affected with the
inconsistent Variable naming.

Therefore i have to thank for your valuable scripts.

**Comment by pageauc** [comment]
Both readme.md files have now been updated.  I have a V2 cam but have not used it with speed cam.  Not sure when I will get auto calibration working reliably since we are getting ready to travel south for the winter.  
Auto Calibration  would depend on the fact that smaller cars are travelling in the field of view (not in an area with only larger vehicles).  eg smaller Honda's, Toyota, KIA, Etc.  Most of these smaller vehicles are very similar in length.  Also cars can travel on either side of the road so there should be a slight correction for vehicles travelling on the far lane going in the opposite direction.  This should be done.  I program assumes a two lane road for best accuracy (not 4 or more).  Like I said this is a demo and there are lots of things that could be done to improve it.  I only do this because I like programming challenges.
